### ISSUE TITLE
Ng Client reviews.service.ts endpoint has extra string with value "search"

### ISSUE THREAD

**Issue by AlexanderLundin** [Tech-Student-Labs/gmdb-client#4]
Here is a link to the endpoints we created per postman documentation:

https://documenter.getpostman.com/view/6945911/SzS1SntF?version=latest#dba8ff54-5084-4a32-941c-ac515816d6d6

The NG client needs a little re-work to match postman endpoints:

GET Get all Reviews
gmdb-dev.robwing.com:8000/api/reviews

POST Post a new review
gmdb-dev.robwing.com:8000/api/reviews

GET Get reviews for email
gmdb-dev.robwing.com:8000/api/reviews?email=user@gmdb.com

GET Get reviews for imdbid
gmdb-dev.robwing.com:8000/api/reviews?email=user@gmdb.com&imdbid=tt3896198

GET Get review by id
gmdb-dev.robwing.com:8000/api/reviews/199

PATCH Update an existing review
gmdb-dev.robwing.com:8000/api/reviews/193

**Comment by Protosac** [comment]
This is correct. I think a case of copy/pasta on my part (from movies service :)) Will push update.
